### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#20]
Working out of this folder: `/nfs/latdata/iamjli/ALS/GarNet/`

Did the following on node19:

```
git clone <garnet repository>
virtualenv venv
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install -r requirements.txt
```

All requirements downloaded successfully with no error. I loaded all relevant data and from `src/` ran 

`python testing.py`

Got this error: 

```
Traceback (most recent call last):
  File "testing.py", line 3, in <module>
    from garnet import *
  File "/nfs/latdata/iamjli/ALS/GarNet/src/garnet.py", line 303
    motifs_and_genes = [{**motif, **gene, **peak} for peak, genes, motifs in peaks_with_associated_genes_and_motifs for gene in genes for motif in motifs]
                          ^
SyntaxError: invalid syntax
```

Then tried creating an instance of python3 and importing garnet, but got the same error.

**Comment by zfrenchee** [comment]
That line requires python 3.5 or above. @iamjli would you mind checking what version of python3 you were running?

**Comment by iamjli** [comment]
3.4 :o

**Comment by zfrenchee** [comment]
That'll do it.
