### ISSUE TITLE
Python version compatability

### ISSUE THREAD

**Issue by agitter** [fraenkel-lab/GarNet#22]
I noticed in `setup.py` that GarNet is compatible with Python 3.5 and 3.6.  Are there Python 3 features being used that prevent it from being compatible with Python 2.7?

I'm also curious if this rewrite is closer to being compatible with both Linux and Windows.  Some path handling code in the original Omics Integrator made it Linux-only.

**Comment by zfrenchee** [comment]
@agitter Yes, there are python 3.5 features being used in GarNet. Python 3.4 are incompatible. This is obviously somewhat unfortunate, and wasn't strictly necessary, but it was a choice we made very early on. Is 2.7 a requisite feature for you? 

Supporting both unix and windows is definitely something we're thinking about. My hope is that we can accomplish this in the packaging/wrapping code. Everything in GarNet right now should be using python's `os.path` which will work with any OS. [Garnet is also dockerized](https://biocontainers.pro/registry/#/showImages?domain=quay&repository=garnet&starred=false&modified=22%2F03%2F2017) which might be a shortcut solution to this problem.

**Comment by agitter** [comment]
No, Python 2.7 isn't a requirement for me.  I was just curious.  Now that I use Anaconda heavily, switching between 2.7 and 3.5 isn't a problem unless I need one package that is stuck on 2.7 and another that is >= 3.x.  I agree it's better to support the modern Python releases.
