### ISSUE TITLE
check files exist

### ISSUE THREAD

**Issue by AmandaKedaigle** [fraenkel-lab/GarNet#32]
Easy one :)

In map_peaks (and similar), can we run a check that all input files exist _before_ attempting to open the garnet_file? Since that step takes a while to run, I'd rather realize I have a typo before waiting for that.

**Comment by zfrenchee** [comment]
Solved in 66061936e90404f501c0b3d26eaf1332afdabce9. Not bumping version number or pushing update to pypi yet, since this isn't a "bug" per se.
