### ISSUE TITLE
What does motif score mean? 

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#33]
Is this the same as binding affinity? If so, shouldn't we filter out motif scores that are 0? About 1 out of 17.3 million motifs are 0. 

@zfrenchee

**Comment by AmandaKedaigle** [comment]
Originally we used FDR from MotifMap (paper which explains score here https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-495) but then I think Alex did some kind of normalization on it

**Comment by zfrenchee** [comment]
I don't believe there's any normalization. 

https://github.com/fraenkel-lab/GarNet/blob/master/GarNet/garnet.py#L163

Is there an issue with 0-score motifs?

**Comment by iamjli** [comment]
Ideally, the motif score would map linearly to binding affinity, so it's strange to see points that lie on the y-axis of the scatter plots.

**Comment by iamjli** [comment]
If we are going to reevaluate motif matching, we should also take a look at [this work](https://academic.oup.com/nar/article/42/5/2976/1050297/Systematic-discovery-and-characterization-of#43262948) out of the Kellis lab.

**Comment by AmandaKedaigle** [comment]
That was published in 2013, so theoretically the PWMs they found should have been included in TRANSFAC and JASPAR, and already be in MotifMap. I don't know that they got that specific paper but the version we got from them was updated in 2014. Is there a reason you like that paper specifically?

**Comment by iamjli** [comment]
They combined motifs from 5 sources, including TRANSFAC and JASPAR: 

> We found that no single algorithm or database comprehensively assays the motifs relevant to the binding diversity surveyed by ENCODE. Therefore, our approach was to collect motifs from several literature sources (11–16) and supplement them with motifs discovered de novo on the data sets themselves using five established tools (17–21)

Their motif file also contains proteins in the correct namespace, so that's a small plus over motifmap. Not sure if it's been updated since 2014, but just a suggestion.

**Comment by AmandaKedaigle** [comment]
Oh OK, from the abstract I thought they had just refined PWMs using ENCODE data. I am not married to MotifMap at all, we should compare these, and keep looking for others! One thing to consider is that it looks like they only provide human matches, whereas motifmap also has mm9 and mm10, which I think is important. I also just downloaded their matches.txt file and they don't provide any kind of affinity scores. They do have "matches for the shuffled control motifs (indicated with _C#)" so we could potentially calculate our own FDR-like scores, but that doesn't improve on your original question about the scores.

I think no matter which data source we use, we need to think carefully about what kind of score we want to use in the regression.

**Comment by zfrenchee** [comment]
@AmandaKedaigle "normalized" meant namespace-normalized, so I changed the names of the genes/TFs so they matched the rest of our names/belonged to the same namespace.

**Comment by AmandaKedaigle** [comment]
After conversation with Ernest, we should definitely switch MotifMap from FDR to NLOD scores, and avoid using conservation as part of our scores. We should still compare MotifMap with other sources, but let's use NLOD for those comparisons.

I was going to switch this in the code myself, but it looks like the parse_motifs_file function is not being used anymore since we've switched to bedtools? Is there still a way to make your own motifs file included with garnet, or should we delete that function from garnet.py and require motifs file to be formatted a certain way?

(I am fine with either way, personally, especially if we are able to eventually include a preprocessed correctly formatted version of human+mice motif files when we distribute GarNet)

**Comment by iamjli** [comment]
Agreed. 

Alex made the argument that it may come useful for cleaning up MotifMap data, which I agreed with initially. 

But the data can be cleaned via command line very quickly, so don't think we really need this function anymore. Here's the command I used: 

`cat motifMap_hg19.tsv | awk -F'\t' '{ print $5 "\t" $8 "\t" $14 "\t" $3 "\t" $12 "\t" $7}' |tr -d \" | sort -k1,1 -k2,2n > motifMap.NLOD.bed`

Output here: 

`/nfs/latdata/iamjli/packages/GarNet2/garnet_data/garnetDB.hg19.NLOD.10kb.tsv`.

**Comment by iamjli** [comment]
Would be great to have something like this from chromVar: https://github.com/GreenleafLab/chromVARmotifs

**Comment by zfrenchee** [comment]
What's the status on this issue?

**Comment by iamjli** [comment]
I'm exploring the motif score/TF affinity metric in depth, and it will take a while, so I'm okay with closing this issue for now.
