### ISSUE TITLE
Bedtools can perform map_peaks function in ~1 min

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#35]
We should probably use bedtools for large genome manipulations since it's super fast. I'm pretty sure it doesn't even need to load the entire motif file in either, but I haven't explicitly tested memory requirements. There's even a [python package](https://pypi.python.org/pypi/pybedtools). 

Here's the workflow: 

## Bedtools intersect notes
Tutorial: [bedtools Tutorial](http://quinlanlab.org/tutorials/bedtools/bedtools.html)
Test directory: `/nfs/latdata/iamjli/test_projects/bedtools/test`
Visualize bed file in IGV

Command to find full overlap: 
`bedtools intersect -a test_motifs.bed -b test_exons.bed -wa -f 1`

Sorting will speed things up: add `-sorted` flag

If not sorted: `sort -k1,1 -k2,2n foo.bed > foo.sort.bed`

## Intersecting GarNet motifs
Motif file: `/nfs/latdata/iamjli/test_projects/bedtools/garnet_data/old/garnetDB.tsv` (3.3 gb)

First sort (7 min): 
`sort -k1,1 -k2,2n garnet_data/old/garnetDB.tsv > garnetDB.sort.bed`

Sort without header: 
`(tail -n +2 garnet_data/old/garnetDB.tsv | sort -k1,1 -k2,2n) > garnetDB.sorted.bed`

Sort ATAC-seq DOS bed file from `/nfs/latdata/iamjli/ALS/ATAC-seq/iMNs_ALS_SMA_CTR_from_iMPs/diffBind_042617`: 
`(tail -n +2 diffSites_ALS_CTR.stripped.txt | sort -k1,1 -k2,2n) > diffSites_ALS_CTR.sorted.bed`

Find intersection (73 s): 
`bedtools intersect -a garnetDB.sorted.bed -b diffSites_ALS_CTR.sorted.bed -wa -f 1 > overlapping_motifs.tsv`

With `-sorted` flag (77 s): 
`bedtools intersect -a garnetDB.sorted.bed -b diffSites_ALS_CTR.sorted.bed -wa -f 1 -sorted > overlapping_motifs.fast.tsv`

**Comment by CSBioAzim** [comment]
It's widely used and i think it's cool tool to use this task as well. 
All the functions are heavily optimised for speed.

**Comment by zfrenchee** [comment]
Seems like a good idea. We weren't doing this before because we weren't using motifmap (now we are) and we wanted to test variable windows around tss' (now 10kb is default).

**Comment by iamjli** [comment]
Variable windows can still be implemented following the intersection step, as there's a column with motif-gene distance.

**Comment by zfrenchee** [comment]
Which column on which file are you thinking about?

**Comment by AmandaKedaigle** [comment]
(Im assuming...) motif_to_gene_distance in the garnet file

**Comment by iamjli** [comment]
Implementation in #36

**Comment by iamjli** [comment]
Merged.
