### ISSUE TITLE
TF regression drop duplicates

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#38]
I'm unclear why duplicates are being removed. It's possible that a gene has the same motif more than once nearby, and I believe these should be considered separately. Or at least keep the one that's closer to the TSS or something. 

https://github.com/fraenkel-lab/GarNet/blob/831a711425c60346d205ab8d8f243d4583d604d9/GarNet/garnet.py#L241

**Comment by zfrenchee** [comment]
@iamjli I believe this is here to deal with the case when the expression file contains the same gene symbol twice. Two different expressions for the same gene doesn't make sense, right?

**Comment by zfrenchee** [comment]
I agree though that if that's what it's for, it's a couple lines below where it should be, I think. There might have been a reason I did it this way, but I forget.

**Comment by zfrenchee** [comment]
#41 addresses this, I think. @iamjli ?

**Comment by iamjli** [comment]
Yea, I think this is something that needs to be tested. The OI paper had a special function that combined these motifs, so I'll test that as well. Will close this for now.
