### ISSUE TITLE
mm9, mm10 garnet file construction notebooks

### ISSUE THREAD

**Issue by zfrenchee** [fraenkel-lab/GarNet#46]
Not urgent, but definitely nice to have. cisDB has these files I think?

**Comment by iamjli** [comment]
Yes, generating mm10 files are almost done: `/nfs/latdata/iamjli/packages/GarNet2/garnet_data/cisBP_mm10`

**Comment by zfrenchee** [comment]
@iamjli does that include adding notebooks to this repo, or is this work in the other repo?

**Comment by iamjli** [comment]
GarNetMotifs is used to generate motif files (bed files that define predicted TF binding sites). Then use GarNet scripts to generate the GarNet files.
