### ISSUE TITLE
Window optional param

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/GarNet#47]
@zfrenchee Could you add a few lines that lets this function take window size as an optional parameter? Not too familiar with the syntax myself. Thanks!

https://github.com/fraenkel-lab/GarNet/blob/8656334b8758fb0f8f486caafeb2f4362070aab3/GarNet/garnet.py#L238

Specifically, do 2kb window if window size is not specified.

**Comment by zfrenchee** [comment]
@iamjli can I still help with this or has this been resolved?

**Comment by iamjli** [comment]
Has not been resolved yet, do you mind taking care of it if it's a quick fix?

**Comment by zfrenchee** [comment]
see #51
